2024-01-16 17:45:01,152 - main.py - main - INFO - starting main application
2024-01-16 17:45:01,152 - main.py - main - INFO - starting handling country: Belarus
2024-01-16 17:45:01,152 - file_handler.py - get_file - INFO - file list: 2
2024-01-16 17:45:01,152 - main.py - main - INFO - finished handling country: Belarus
2024-01-16 17:45:37,243 - main.py - main - INFO - starting main application
2024-01-16 17:45:37,243 - main.py - main - INFO - starting handling country: Belarus
2024-01-16 17:45:37,243 - file_handler.py - get_file - INFO - file list: 2
2024-01-16 17:45:37,243 - main.py - main - INFO - finished handling country: Belarus
2024-01-16 17:46:53,579 - main.py - main - INFO - starting main application
2024-01-16 17:46:53,579 - main.py - main - INFO - starting handling country: Belarus
2024-01-16 17:46:53,579 - file_handler.py - get_file - INFO - file list: 2
2024-01-16 17:46:53,579 - main.py - main - ERROR - Could not get source mnp file
Traceback (most recent call last):
  File "/Users/andrey/Documents/work/mnp/mnp_parsing_refactoring/main.py", line 22, in main
    raw_mnp_file = file_handler.get_file()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey/Documents/work/mnp/mnp_parsing_refactoring/file_handlers/file_handler.py", line 123, in get_file
    logger.info(f'to many files in source directory: {belarus_settings.destination_directory}')
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey/Documents/work/mnp/mnp_parsing_refactoring/.venv/lib/python3.11/site-packages/pydantic/main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'BelarusMnpSettings' object has no attribute 'destination_directory'
2024-01-16 17:46:53,580 - main.py - main - ERROR - cannot access local variable 'raw_mnp_file' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/andrey/Documents/work/mnp/mnp_parsing_refactoring/main.py", line 28, in main
    parse_result = parser.parse(raw_mnp_file)
                                ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'raw_mnp_file' where it is not associated with a value
2024-01-16 17:46:53,580 - main.py - main - INFO - finished handling country: Belarus
2024-01-16 17:47:33,160 - main.py - main - INFO - starting main application
2024-01-16 17:47:33,160 - main.py - main - INFO - starting handling country: Belarus
2024-01-16 17:47:33,160 - file_handler.py - get_file - INFO - file list: 2
2024-01-16 17:47:33,161 - main.py - main - ERROR - Could not get source mnp file
Traceback (most recent call last):
  File "/Users/andrey/Documents/work/mnp/mnp_parsing_refactoring/main.py", line 22, in main
    raw_mnp_file = file_handler.get_file()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey/Documents/work/mnp/mnp_parsing_refactoring/file_handlers/file_handler.py", line 123, in get_file
    logger.info(f'to many files in source directory: {belarus_settings.destination_directory}')
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey/Documents/work/mnp/mnp_parsing_refactoring/.venv/lib/python3.11/site-packages/pydantic/main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'BelarusMnpSettings' object has no attribute 'destination_directory'
2024-01-16 17:47:33,162 - main.py - main - ERROR - cannot access local variable 'raw_mnp_file' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/andrey/Documents/work/mnp/mnp_parsing_refactoring/main.py", line 28, in main
    parse_result = parser.parse(raw_mnp_file)
                                ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'raw_mnp_file' where it is not associated with a value
2024-01-16 17:47:33,162 - main.py - main - INFO - finished handling country: Belarus
2024-01-16 17:48:20,048 - main.py - main - INFO - starting main application
2024-01-16 17:48:20,048 - main.py - main - INFO - starting handling country: Belarus
2024-01-16 17:48:20,048 - file_handler.py - get_file - INFO - file list: 2
2024-01-16 17:48:20,048 - main.py - main - ERROR - Could not get source mnp file
Traceback (most recent call last):
  File "/Users/andrey/Documents/work/mnp/mnp_parsing_refactoring/main.py", line 22, in main
    raw_mnp_file = file_handler.get_file()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey/Documents/work/mnp/mnp_parsing_refactoring/file_handlers/file_handler.py", line 123, in get_file
    logger.info(f'to many files in source directory: {belarus_settings.destination_directory}')
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey/Documents/work/mnp/mnp_parsing_refactoring/.venv/lib/python3.11/site-packages/pydantic/main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'BelarusMnpSettings' object has no attribute 'destination_directory'
2024-01-16 17:48:20,049 - main.py - main - INFO - finished handling country: Belarus
2024-01-16 17:48:36,563 - main.py - main - INFO - starting main application
2024-01-16 17:48:36,563 - main.py - main - INFO - starting handling country: Belarus
2024-01-16 17:48:36,563 - file_handler.py - get_file - INFO - file list: 2
2024-01-16 17:48:36,563 - file_handler.py - get_file - INFO - to many files in source directory: /Users/andrey/Downloads/mnp/tmp/belarus
2024-01-16 17:48:36,563 - main.py - main - ERROR - Could not get source mnp file
2024-01-16 17:48:36,563 - main.py - main - INFO - finished handling country: Belarus
2024-01-16 17:49:07,917 - main.py - main - INFO - starting main application
2024-01-16 17:49:07,917 - main.py - main - INFO - starting handling country: Belarus
2024-01-16 17:49:07,918 - file_handler.py - get_file - INFO - file list: 2
2024-01-16 17:49:07,918 - file_handler.py - get_file - WARNING - to many files in source directory: /Users/andrey/Downloads/mnp/tmp/belarus
2024-01-16 17:49:07,918 - main.py - main - ERROR - Could not get source mnp file
2024-01-16 17:49:07,918 - main.py - main - INFO - finished handling country: Belarus
2024-01-16 17:49:36,601 - main.py - main - INFO - starting main application
2024-01-16 17:49:36,602 - main.py - main - INFO - starting handling country: Belarus
2024-01-16 17:49:36,602 - file_handler.py - get_file - INFO - file list: 1
2024-01-16 17:49:36,602 - file_handler.py - get_file - INFO - source mnp file: /Users/andrey/Downloads/mnp/tmp/belarus/MNP_BY_2024_01_15.xlsx
2024-01-16 17:49:36,602 - parser.py - parse - INFO - starting parsing Belarus mnp file
2024-01-16 17:49:51,521 - parser.py - parse - ERROR - An error occurred while parsing record ('RECEPTOR_NETWORK_ID', 'MSISDN', 'PORTED_TIME')
Traceback (most recent call last):
  File "/Users/andrey/Documents/work/mnp/mnp_parsing_refactoring/parsers/parser.py", line 92, in parse
    datetime.datetime.strptime(port_date_cell.value, '%d.%m.%Y %H:%M:%S').timestamp()),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'PORTED_TIME' does not match format '%d.%m.%Y %H:%M:%S'
2024-01-16 17:49:54,904 - main.py - main - DEBUG - remove raw mnp file: /Users/andrey/Downloads/mnp/tmp/belarus/MNP_BY_2024_01_15.xlsx
2024-01-16 17:49:54,904 - utils.py - archive_file - DEBUG - Starting archiving /Users/andrey/Downloads/mnp/tmp/belarus/MNP_BY_2024_01_15.xlsx
2024-01-16 17:49:54,904 - utils.py - archive_file - DEBUG - Archive path: /Users/andrey/Downloads/mnp/archive/Belarus-20240116.zip
2024-01-16 17:49:54,923 - utils.py - archive_file - DEBUG - Finished archiving
2024-01-16 17:49:54,933 - file_handler.py - save_parse_result - INFO - start save parse result
2024-01-16 17:49:54,933 - file_handler.py - save_parse_result - INFO - saving ftp file to: /Users/andrey/Downloads/mnp/ftp/belarus/belarus.csv
2024-01-16 17:49:54,933 - main.py - main - ERROR - 'NoneType' object has no attribute 'hlr_records'
Traceback (most recent call last):
  File "/Users/andrey/Documents/work/mnp/mnp_parsing_refactoring/main.py", line 33, in main
    file_handler.save_parse_result(parse_result)
  File "/Users/andrey/Documents/work/mnp/mnp_parsing_refactoring/file_handlers/file_handler.py", line 140, in save_parse_result
    csv_writer.writerows(parsed_result.hlr_records)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'hlr_records'
2024-01-16 17:49:54,937 - main.py - main - INFO - finished handling country: Belarus
2024-01-16 18:02:16,375 - main.py - main - INFO - starting main application
2024-01-16 18:02:16,375 - main.py - main - INFO - starting handling country: Belarus
2024-01-16 18:02:16,375 - file_handler.py - get_file - INFO - file list: 1
2024-01-16 18:02:16,375 - file_handler.py - get_file - INFO - source mnp file: /Users/andrey/Downloads/mnp/tmp/belarus/MNP_BY_2024_01_15.xlsx
2024-01-16 18:02:16,375 - parser.py - parse - INFO - starting parsing Belarus mnp file
2024-01-16 18:02:30,898 - parser.py - parse - ERROR - An error occurred while parsing record ('RECEPTOR_NETWORK_ID', 'MSISDN', 'PORTED_TIME')
Traceback (most recent call last):
  File "/Users/andrey/Documents/work/mnp/mnp_parsing_refactoring/parsers/parser.py", line 92, in parse
    datetime.datetime.strptime(port_date_cell.value, '%d.%m.%Y %H:%M:%S').timestamp()),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'PORTED_TIME' does not match format '%d.%m.%Y %H:%M:%S'
2024-01-16 18:02:34,073 - main.py - main - DEBUG - remove raw mnp file: /Users/andrey/Downloads/mnp/tmp/belarus/MNP_BY_2024_01_15.xlsx
2024-01-16 18:02:34,074 - utils.py - archive_file - DEBUG - Starting archiving /Users/andrey/Downloads/mnp/tmp/belarus/MNP_BY_2024_01_15.xlsx
2024-01-16 18:02:34,074 - utils.py - archive_file - DEBUG - Archive path: /Users/andrey/Downloads/mnp/archive/Belarus-20240116.zip
2024-01-16 18:02:34,096 - utils.py - archive_file - DEBUG - Finished archiving
2024-01-16 18:02:34,104 - file_handler.py - save_parse_result - INFO - start save parse result
2024-01-16 18:02:34,104 - file_handler.py - save_parse_result - INFO - saving ftp file to: /Users/andrey/Downloads/mnp/ftp/belarus/belarus.csv
2024-01-16 18:02:34,498 - file_handler.py - save_parse_result - INFO - saving hlr3 file to: /Users/andrey/Downloads/mnp/hlr/belarus/belarus.csv
2024-01-16 18:02:35,082 - main.py - main - INFO - finished handling country: Belarus
2024-01-16 18:05:27,536 - main.py - main - INFO - starting main application
2024-01-16 18:05:27,536 - main.py - main - INFO - starting handling country: Belarus
2024-01-16 18:05:27,536 - file_handler.py - get_file - INFO - file list: 0
2024-01-16 18:05:27,536 - file_handler.py - get_file - WARNING - file not found in source directory: /Users/andrey/Downloads/mnp/tmp/belarus
2024-01-16 18:05:27,536 - main.py - main - ERROR - Could not get source mnp file
2024-01-16 18:05:27,536 - main.py - main - INFO - finished handling country: Belarus
2024-01-17 15:37:19,372 - main.py - main - INFO - starting main application
2024-01-17 15:37:19,372 - main.py - main - INFO - starting handling country: Belarus
2024-01-17 15:37:19,373 - file_handler.py - get_file - INFO - file list: 0
2024-01-17 15:37:19,373 - file_handler.py - get_file - WARNING - file not found in source directory: /Users/andrey/Downloads/mnp/tmp/belarus
2024-01-17 15:37:19,373 - main.py - main - ERROR - Could not get source mnp file
2024-01-17 15:37:19,373 - main.py - main - INFO - finished handling country: Belarus
2024-01-17 15:37:19,373 - main.py - main - INFO - Archive full hlr file
2024-01-17 15:37:19,373 - utils.py - archive_file - DEBUG - Starting archiving /Users/andrey/Downloads/mnp/hlr/hlr3_full.csv
2024-01-17 15:37:19,373 - utils.py - archive_file - DEBUG - Archive file: /Users/andrey/Downloads/mnp/archive/full_hlr-20240117.zip
2024-01-17 15:59:41,631 - main.py - main - INFO - starting main application
2024-01-17 15:59:41,632 - main.py - main - INFO - starting handling country: Belarus
2024-01-17 15:59:41,633 - file_handler.py - get_file - INFO - file list: 0
2024-01-17 15:59:41,633 - file_handler.py - get_file - WARNING - file not found in source directory: /Users/andrey/Downloads/mnp/tmp/belarus
2024-01-17 15:59:41,633 - main.py - main - ERROR - Could not get source mnp file
2024-01-17 15:59:41,633 - main.py - main - INFO - finished handling country: Belarus
2024-01-17 15:59:41,633 - main.py - main - INFO - Archive full hlr file
2024-01-17 15:59:41,633 - utils.py - archive_file - DEBUG - Starting archiving /Users/andrey/Downloads/mnp/hlr/hlr3_full.csv
2024-01-17 15:59:41,633 - utils.py - archive_file - DEBUG - Archive file: /Users/andrey/Downloads/mnp/archive/full_hlr-20240117.zip
2024-01-17 16:00:35,210 - main.py - main - INFO - starting main application
2024-01-17 16:00:35,211 - main.py - main - INFO - starting handling country: Belarus
2024-01-17 16:00:35,212 - file_handler.py - get_file - INFO - file list: 0
2024-01-17 16:00:35,212 - file_handler.py - get_file - WARNING - file not found in source directory: /Users/andrey/Downloads/mnp/tmp/belarus
2024-01-17 16:00:35,212 - main.py - main - ERROR - Could not get source mnp file
2024-01-17 16:00:35,212 - main.py - main - INFO - finished handling country: Belarus
2024-01-17 16:00:35,212 - main.py - main - INFO - Archive full hlr file
2024-01-17 16:00:35,212 - utils.py - archive_file - DEBUG - Starting archiving /Users/andrey/Downloads/mnp/hlr/hlr3_full.csv
2024-01-17 16:00:35,212 - utils.py - archive_file - DEBUG - Archive file: /Users/andrey/Downloads/mnp/archive/full_hlr-20240117.zip
2024-01-17 16:00:35,212 - utils.py - archive_file - DEBUG - Finished archiving
2024-01-17 16:00:35,212 - file_handler.py - join_all_files - INFO - Start joining all files
2024-01-17 16:00:35,307 - file_handler.py - join_all_files - INFO - Finish joining all files
2024-01-17 16:00:35,311 - utils.py - push_file_to_server - INFO - Pushing /Users/andrey/Downloads/mnp/hlr/hlr3_full.csv to 89.31.240.234:/tmp/
2024-01-17 16:03:31,311 - main.py - main - INFO - starting main application
2024-01-17 16:03:31,312 - main.py - main - INFO - starting handling country: Belarus
2024-01-17 16:03:31,312 - file_handler.py - get_file - INFO - file list: 0
2024-01-17 16:03:31,312 - file_handler.py - get_file - WARNING - file not found in source directory: /Users/andrey/Downloads/mnp/tmp/belarus
2024-01-17 16:03:31,312 - main.py - main - ERROR - Could not get source mnp file
2024-01-17 16:03:31,312 - main.py - main - INFO - finished handling country: Belarus
2024-01-17 16:03:31,312 - main.py - main - INFO - Archive full hlr file
2024-01-17 16:03:31,312 - utils.py - archive_file - DEBUG - Starting archiving /Users/andrey/Downloads/mnp/hlr/hlr3_full.csv
2024-01-17 16:03:31,313 - utils.py - archive_file - DEBUG - Archive file: /Users/andrey/Downloads/mnp/archive/full_hlr-20240117.zip
2024-01-17 16:03:31,335 - utils.py - archive_file - DEBUG - Finished archiving
2024-01-17 16:03:31,335 - file_handler.py - join_all_files - INFO - Start joining all files
2024-01-17 16:03:31,430 - file_handler.py - join_all_files - INFO - Finish joining all files
2024-01-17 16:03:31,434 - utils.py - push_file_to_server - INFO - Pushing /Users/andrey/Downloads/mnp/hlr/hlr3_full.csv to 89.31.240.234:/tmp/
2024-01-17 16:03:50,443 - main.py - main - INFO - starting main application
2024-01-17 16:03:50,444 - main.py - main - INFO - starting handling country: Belarus
2024-01-17 16:03:50,444 - file_handler.py - get_file - INFO - file list: 0
2024-01-17 16:03:50,444 - file_handler.py - get_file - WARNING - file not found in source directory: /Users/andrey/Downloads/mnp/tmp/belarus
2024-01-17 16:03:50,444 - main.py - main - ERROR - Could not get source mnp file
2024-01-17 16:03:50,444 - main.py - main - INFO - finished handling country: Belarus
2024-01-17 16:03:50,444 - main.py - main - INFO - Archive full hlr file
2024-01-17 16:03:50,444 - utils.py - archive_file - DEBUG - Starting archiving /Users/andrey/Downloads/mnp/hlr/hlr3_full.csv
2024-01-17 16:03:50,444 - utils.py - archive_file - DEBUG - Archive file: /Users/andrey/Downloads/mnp/archive/full_hlr-20240117.zip
2024-01-17 16:03:50,463 - utils.py - archive_file - DEBUG - Finished archiving
2024-01-17 16:03:50,463 - file_handler.py - join_all_files - INFO - Start joining all files
2024-01-17 16:03:50,562 - file_handler.py - join_all_files - INFO - Finish joining all files
2024-01-17 16:03:50,567 - utils.py - push_file_to_server - INFO - Pushing /Users/andrey/Downloads/mnp/hlr/hlr3_full.csv to 89.31.240.234:/tmp/
2024-01-18 13:35:28,235 - main.py - main - INFO - starting main application
2024-01-18 13:35:28,235 - main.py - main - INFO - starting handling country: Belarus
2024-01-18 13:35:28,236 - file_handler.py - get_file - INFO - file list: 0
2024-01-18 13:35:28,236 - file_handler.py - get_file - WARNING - file not found in source directory: /Users/andrey/Downloads/mnp/tmp/belarus
2024-01-18 13:35:28,236 - main.py - main - ERROR - Could not get source mnp file
2024-01-18 13:35:28,236 - main.py - main - INFO - finished handling country: Belarus
2024-01-18 13:35:28,236 - main.py - main - INFO - Archive full hlr file
2024-01-18 13:35:28,236 - utils.py - archive_file - DEBUG - Starting archiving /Users/andrey/Downloads/mnp/hlr/hlr3_full.csv
2024-01-18 13:35:28,236 - utils.py - archive_file - DEBUG - Archive file: /Users/andrey/Downloads/mnp/archive/full_hlr-20240118.zip
2024-01-18 13:35:28,279 - utils.py - archive_file - DEBUG - Finished archiving
2024-01-18 13:35:28,279 - file_handler.py - join_all_files - INFO - Start joining all files
2024-01-18 13:35:28,369 - file_handler.py - join_all_files - INFO - Finish joining all files
2024-01-18 13:35:28,375 - utils.py - push_file_to_server - INFO - Pushing /Users/andrey/Downloads/mnp/hlr/hlr3_full.csv to 89.31.240.234:/tmp/
2024-01-18 13:37:10,836 - main.py - main - INFO - starting main application
2024-01-18 13:37:10,836 - main.py - main - INFO - starting handling country: Belarus
2024-01-18 13:37:10,837 - file_handler.py - get_file - INFO - file list: 0
2024-01-18 13:37:10,837 - file_handler.py - get_file - WARNING - file not found in source directory: /Users/andrey/Downloads/mnp/tmp/belarus
2024-01-18 13:37:10,837 - main.py - main - ERROR - Could not get source mnp file
2024-01-18 13:37:10,837 - main.py - main - INFO - finished handling country: Belarus
2024-01-18 13:37:10,837 - main.py - main - INFO - Archive full hlr file
2024-01-18 13:37:10,837 - utils.py - archive_file - DEBUG - Starting archiving /Users/andrey/Downloads/mnp/hlr/hlr3_full.csv
2024-01-18 13:37:10,837 - utils.py - archive_file - DEBUG - Archive file: /Users/andrey/Downloads/mnp/archive/full_hlr-20240118.zip
2024-01-18 13:37:10,870 - utils.py - archive_file - DEBUG - Finished archiving
2024-01-18 13:37:10,870 - file_handler.py - join_all_files - INFO - Start joining all files
2024-01-18 13:37:10,973 - file_handler.py - join_all_files - INFO - Finish joining all files
2024-01-18 13:37:10,978 - utils.py - push_file_to_server - INFO - Pushing /Users/andrey/Downloads/mnp/hlr/hlr3_full.csv to 89.31.240.234:/tmp/
2024-01-18 13:42:21,128 - main.py - main - INFO - starting main application
2024-01-18 13:42:21,129 - main.py - main - INFO - starting handling country: Belarus
2024-01-18 13:42:21,129 - file_handler.py - get_file - INFO - file list: 0
2024-01-18 13:42:21,129 - file_handler.py - get_file - WARNING - file not found in source directory: /Users/andrey/Downloads/mnp/tmp/belarus
2024-01-18 13:42:21,129 - main.py - main - ERROR - Could not get source mnp file
2024-01-18 13:42:21,129 - main.py - main - INFO - finished handling country: Belarus
2024-01-18 13:42:21,129 - main.py - main - INFO - Archive full hlr file
2024-01-18 13:42:21,129 - utils.py - archive_file - DEBUG - Starting archiving /Users/andrey/Downloads/mnp/hlr/hlr3_full.csv
2024-01-18 13:42:21,129 - utils.py - archive_file - DEBUG - Archive file: /Users/andrey/Downloads/mnp/archive/full_hlr-20240118.zip
2024-01-18 13:42:21,151 - utils.py - archive_file - DEBUG - Finished archiving
2024-01-18 13:42:21,152 - file_handler.py - join_all_files - INFO - Start joining all files
2024-01-18 13:42:21,240 - file_handler.py - join_all_files - INFO - Finish joining all files
2024-01-18 13:42:21,245 - utils.py - push_file_to_server - INFO - Pushing /Users/andrey/Downloads/mnp/hlr/hlr3_full.csv to 89.31.240.234:/tmp/
